acc/urls.py
from django.urls import path
from acc import views

app_name = "acc"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("signup/", views.signup, name="signup")
]

cocnfig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser) :
    comment = models.TextField()
    point = models.IntegerField(default=0)
    age = models.IntegerField(default=0)
    pic = models.ImageField(upload_to="user/%y/%m")
    

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User

# Create your views here.

def index(request) :
    return render (request, "acc/index.html")

def login_user(request) :
    if request.method == "POST" :
        un = request.POST.get("uname")
        pw = request.POST.get("upass")
        user = authenticate(username=un, password=pw)
        if user :
            login(request, user)
            return redirect("acc:index")
        else :
            pass
    return render(request, "acc/login.html")

def logout_user(request) :
    logout(request)
    return redirect ("acc:login")

def signup(request) :
    if request.method == "POST" :
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        ua = request.POST.get("uage")
        uc = request.POST.get ("ucom")
        pi = request.FILES.get("upic")
        try :
            User.objects.create_user(username=un, password=up, age=ua, comment=uc, pic=pi)
            return redirect("acc:login")
        except :
            pass
    return render (request, "acc/signup.html")

templates/acc/index.html
{% extends 'base.html' %} 

{% block con %} 
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">SEVENTEEN COVER VOCAL TEAM AN ODE </h1>
            <p class="col-md-8 fs-4">된장찌개 좋아하시는 분 나가세요!</p>
            <a href="{%url 'acc:login' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">LOGIN</button></a>
        </div>
    </div>
{% endblock %} 

templates/acc/login.html
{% extends 'base.html' %} 

{% block con %} 
    <div class="container mt-5 mb-5" style="width: 60%;">
        <h1><b>로그인</b></h1>
        <form method="post">
            {% csrf_token %}
            <div class="mt-5">
        
                <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME" style="font-weight: bold;">
                <input type="password" name="upass" class="form-control mt-4" placeholder="INPUT PASSWORD" style="font-weight: bold;">
            </div>
            <div class="text-end mt-4">
                <button class="btn btn-dark">LOGIN</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}   

{% block con %}  
    <div class="container mt-5 mb-5" style="width: 60%; font-weight: bold; font-size: 20px;">
        <h1><b>회원가입</b></h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label for="exampleInputEmail1" class="form-label">USERNAME</label>
                <input type="text" name="uname" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">PASSWORD</label>
                <input type="password" name="upass" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">AGE</label>
                <input type="number" name="uage" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">COMMENT</label>
                <textarea name="ucom" class="form-control"></textarea>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">USERPIC</label>
                <input name="upic" type="file" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mt-4 text-end">
                <button type="submit" class="btn btn-dark" style="font-weight: bold;">회원가입</button> 
            </div>
        </form>
    </div>
{% endblock %} 

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <title>AN ODE</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0); font-size: 20px; font-weight: bold;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">SHOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="#">BOARD</a>
                            </li>
                            
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#">profile</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'acc:logout' %}">logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% else %}
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0); font-size: 20px; font-weight: bold;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">SHOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:login' %}">LOGIN</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:signup' %}">SIGNUP</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% endif %}


        {% block con %}
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>